#! /bin/sh
killall polybar
killall sxhkd
killall picom

sxhkd &
picom &
polybar -r nord &
polybar -r top_external &
xsetroot -cursor_name left_ptr 
feh --bg-scale /home/michael/wallpapers/lake.png

dunst &
xrandr --output eDP-1 --auto --output HDMI-1 --auto --right-of eDP-1

bspc monitor -d I II III IV V VI 
bspc monitor HDMI-1 -d VII VIII IX X

bspc config border_width         4
bspc config window_gap         5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# Mouse
bspc config click_to_focus	 	button1
bspc config focus_follows_pointer 	true

# Monocle mode settings
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle	 true

# Colors
bspc config normal_border_color		"#2e3440"
bspc config focused_border_color	"#1f232b"



